import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { GetServerSideProps } from "next";
import Input from "@/components/Input";
import Cards from "@/components/Cards";
import MobileTab from "@/components/MobileTab";

const BASE_URL = "https://api.npoint.io/579627c7c76816eaf4e3";
export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>HTTP analysis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.status}>
          <div className={styles.status_txt}>
            <h2>200</h2>
            <p>Everything is fine</p>
          </div>
          <Input url={BASE_URL} />
        </div>
        <Cards data={data} />
        <MobileTab data={data} />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const response = await fetch(BASE_URL);
  const data = await response.json();
  return { props: { data } };
};
