import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Input from "@/components/Input";

export default function Home() {
  return (
    <>
      <Head>
        <title>HTTP analysis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Input />
        </div>
      </main>
    </>
  );
}
